[FWK-614] cleans up bull job listeners and reworks their logging
greenchef/platform-utils pull request #39
Opened 2021-02-09 22:32 UTC by Brady-Conn

Ticket: https://greenchef.atlassian.net/browse/FWK-614 
goes with but not dependent on: 
Will need to bump platform util versions in auth and shipping once this is merged and released, related prs:

2021-02-19 16:34 UTC, bearfact commented on jobs/base.bull.job.js
> +				this.logger.debug(`${this.constructor.name} completed in ${executionTime} milliseconds`, { executionTime, attempt: job.attemptsMade, job: this.constructor.name })
lets add the start time in here as well since we have it

2021-02-19 16:42 UTC, aprakash-gc requested changes

2021-02-19 16:42 UTC, aprakash-gc commented on jobs/base.bull.job.js
> +				this.logger.debug(`${this.constructor.name} completed in ${executionTime} milliseconds`, { executionTime, attempt: job.attemptsMade, job: this.constructor.name })
`jobName` should already be getting logged, so i don't think you need the `job` field here

2021-02-19 17:28 UTC, bearfact submitted a review, later dismissed
Love it

2021-02-19 17:44 UTC, aprakash-gc requested changes

2021-02-19 17:44 UTC, aprakash-gc commented on jobs/base.bull.job.js
> +				this.logger.debug(`${this.constructor.name} completed in ${executionTime} milliseconds`, { executionTime, attempt: job.attemptsMade, job: this.constructor.name, startTime })
```suggestion
				this.logger.debug(`${this.constructor.name} completed in ${executionTime} milliseconds`, { executionTime, attempt: job.attemptsMade, startTime })
```

2021-02-19 18:47 UTC, aprakash-gc approved these changes

2021-02-19 21:11 UTC, aprakash-gc approved these changes

2021-02-20 01:58 UTC, bearfact approved these changes

2021-02-22 18:44 UTC, merged